// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Cms__EditorController from "./cms/editor_controller"
application.register("cms--editor", Cms__EditorController)

import Dashboard__ListController from "./dashboard/list_controller"
application.register("dashboard--list", Dashboard__ListController)

import ElementRemovalController from "./element_removal_controller"
application.register("element-removal", ElementRemovalController)

import Flowbite__CollapseController from "./flowbite/collapse_controller"
application.register("flowbite--collapse", Flowbite__CollapseController)

import Flowbite__DropdownController from "./flowbite/dropdown_controller"
application.register("flowbite--dropdown", Flowbite__DropdownController)

import Form__SubmissionController from "./form/submission_controller"
application.register("form--submission", Form__SubmissionController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import Owners__Dashboards__TabController from "./owners/dashboards/tab_controller"
application.register("owners--dashboards--tab", Owners__Dashboards__TabController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
