---
:verbose: false
:concurrency: 10
:queues:
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
  - lb_aoa_staging_default
  - lb_aoa_production_default

production:
  :concurrency: 25

:max_retries: 5
